### ISSUE TITLE
Missing handle bars code snippet in gallery template in repository website

### ISSUE THREAD

**Issue by guti7** [dropbox/dbximages#1]
The [tutorial website](https://dropbox.github.io/nodegallerytutorial/) is missing the handlebars snippet in `/views/gallery.hbs`

```html
<div class="galleria">
    {{#each imgs}}
    <img src="{{this}}">
    {{/each}}
</div>
```

See attached screenshot.
![views gallery hbs](https://user-images.githubusercontent.com/7505855/37883608-4eae480e-3060-11e8-883e-5a61c9a18804.png)

**Comment by rubenrincon** [comment]
Thanks for reporting!
Seems to be an issue with the way that  github.io renders the {{ }}
had to add some escaping to the code ...

`      {% raw %}
        {{#each imgs}}
            <img src="{{this}}">
        {{/each}}
      {% endraw %}`

**Comment by rubenrincon** [comment]
fixed
